# Generated by Django 3.0.5 on 2021-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interface_IA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='weight',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='images',
            name='result',
            field=models.CharField(max_length=200),
        ),
    ]
